---
- name: Show Configurations (IOS)
  hosts: all
  vars:
    ansible_connection: network_cli
    ansible_user: "{{ user }}"
    ansible_ssh_pass: "{{ pass }}"
    ansible_network_os: ios

  tasks:

    - name: Show Run
      ios_command:
        commands: "{{ cmd }}"
      register: show_run

    - debug:
        msg: "{{ show_run.stdout[0] }}"
      tags: [print_action]
